# Generated by Django 4.2.9 on 2024-02-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drowsiness_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SleepDetection',
        ),
    ]
