# Generated by Django 4.2.9 on 2024-03-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drowsiness_app', '0006_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
