# Generated by Django 4.2.9 on 2024-03-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drowsiness_app', '0009_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
